### ISSUE TITLE
browse page - filters as links? & clearing filters

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/mare-browse-filters#1]
When I click on a filtered denomination or state/territory, it doesn't take me anywhere (I'm assuming this will be implemented down the line). If they aren't meant to be links, I think they should just be black instead of blue. 

Another thought is to combine the text and the X as one link so if a user hovers over the text or tabs over to it, the user sees that both will result in the same action.
![Screen Shot 2020-11-02 at 3 13 04 PM](https://user-images.githubusercontent.com/618307/97915165-016c5280-1d1f-11eb-8e09-ea3b48986ee0.png)

Clicking the blue x by them removes the filtered text from view as expected; however the images remain in view instead of resetting to randomized images.
![Screen Shot 2020-11-02 at 3 20 37 PM](https://user-images.githubusercontent.com/618307/97915171-05987000-1d1f-11eb-9bea-c23d506a2390.png)

**Comment by kimisgold** [comment]
The filter names are now plain text, with only the remove buttons remaining obviously interactive elements.

The results won't update dynamically as you remove the filters. To remove the filters and update the results, you need to click on the apply button again. Dynamic updates is technically tricky and would likely slow down the workflow. We also want to make the interface forgiving if the user makes mistakes with arranging the filter query. We're likely to stick with the workflow of "Select/Deselect filters" -> "Click apply to confirm and submit" for those reasons.
